# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gittree < Formula
  desc ""
  homepage "https://github.com/mucansever/gittree"
  version "1.0.5"

  on_macos do
    url "https://github.com/mucansever/gittree/releases/download/v1.0.5/gittree_1.0.5_darwin_all.tar.gz"
    sha256 "919038414cd2164ee1a7b615db0f6982f6b36f01a5ccb91f36b765d6bab5fdf7"

    def install
      bin.install "gittree"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mucansever/gittree/releases/download/v1.0.5/gittree_1.0.5_linux_amd64.tar.gz"
        sha256 "bdcc0a3f5955d29d0bed3090dd3259df2300d56fb721a6ce43a77bc8ef70f9a2"

        def install
          bin.install "bin/gittree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mucansever/gittree/releases/download/v1.0.5/gittree_1.0.5_linux_arm64.tar.gz"
        sha256 "5690b046e19351c63eeda2b9aec485e0c4409b339262e26fd83d887b884339eb"

        def install
          bin.install "bin/gittree"
        end
      end
    end
  end
end
