# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gittree < Formula
  desc ""
  homepage "https://github.com/mucansever/gittree"
  version "0.1.2"

  on_macos do
    url "https://github.com/mucansever/gittree/releases/download/v0.1.2/gittree_0.1.2_darwin_all.tar.gz"
    sha256 "0bca7c259acdc62f68e355c85de34ff6b1357cc0654182939891c3545de63106"

    def install
      bin.install "gittree"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mucansever/gittree/releases/download/v0.1.2/gittree_0.1.2_linux_arm64.tar.gz"
      sha256 "9a6de51734d9a4613f58fcd2174db0cac09475ac85955a99ee0162ae24980a56"

      def install
        bin.install "gittree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mucansever/gittree/releases/download/v0.1.2/gittree_0.1.2_linux_amd64.tar.gz"
      sha256 "8f4e71b8256345fe549f054c73013ba877538ac7db6a3b266519bf3fee225ace"

      def install
        bin.install "gittree"
      end
    end
  end
end
