# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gittree < Formula
  desc ""
  homepage "https://github.com/mucansever/gittree"
  version "1.0.4"

  on_macos do
    url "https://github.com/mucansever/gittree/releases/download/v1.0.4/gittree_1.0.4_darwin_all.tar.gz"
    sha256 "7ca09b7f3de954e5e128d54d7c2c0762c5d79ab418de1b18f42083ba896e080d"

    def install
      bin.install "gittree"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mucansever/gittree/releases/download/v1.0.4/gittree_1.0.4_linux_amd64.tar.gz"
        sha256 "27f518193fad6cfd011a7c9697a53f592f4501fadbc9938ec5809b756856f7dc"

        def install
          bin.install "bin/gittree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mucansever/gittree/releases/download/v1.0.4/gittree_1.0.4_linux_arm64.tar.gz"
        sha256 "f8610a144be26c7e3a938b449a55d04e518001b33b4f51474852ad3876497be5"

        def install
          bin.install "bin/gittree"
        end
      end
    end
  end
end
